INSERT INTO SEMAINE (
        NUM_SEMAINE, FRUIT, TAILLE, POIDS)
        VALUES (
            1,
            'Poussière d\'étoiles',
            '0mm',
            '0'                
        ),
        (
            2,
            'Poussière d\'étoiles',
            '0mm',
            '0'                
        ),
        (
            3,
            'Graine de pavot',
            '1,5mm',
            '0g'                
        ),
        (
            4,
            'Graine de pavot',
            '1,5mm',
            '0g'                
        ),
        (
            5,
            'Graine de sésame',
            '2mm',
            '0g'
        ),
        (
            6,
            'Grain de riz',
            '5mm',
            '1g'
        ),
        (
            7,
            'Myrtille',
            '9,5mm',
            '2g'
        ),
        (
            8,
            'Framboise',
            '1,6cm',
            '5g'
        ),
        (
            9,
            'Raisin',
            '2,3cm',
            '10g'
        ),
        (
            10,
            'Datte',
            '3,1cm',
            '35g'
        ),
        (
            11,
            'Figue',
            '4,1cm',
            '45g'
        ),
        (
            12,
            'Prune',
            '5,4cm',
            '56g'
        ),
        (
            13,
            'Kiwi',
            '6,6cm',
            '74g'

        ),
        (
            14,
            'Pêche',
            '14,7cm',
            '93g'
        ),
        (
            15,
            'Poire',
            '16,7cm',
            '116g'
        ),
        (
            16,
            'Avocat',
            '18,5cm',
            '147g'
        ),
        (
            17,
            'Orange Navel',
            '20,3cm',
            '181g'
        ),
        (
            18,
            'Grenade',
            '22cm',
            '224g'
        ),
        (
            19,
            'Pamplemousse',
            '24,1cm',
            '272g'
        ),
        (
            20,
            'Mangue',
            '25,6cm',
            '331g'    
        ),
        (
            21,
            'Melon',
            '27,4cm',
            '400g'
        ),
        (
            22,
            'Aubergine',
            '28-33cm',
            '453-680g'
        ),
        (
            23,
            'Aubergine',
            '28-33cm',
            '453-680g'
        ),
         (
            24,
            'Aubergine',
            '28-33cm',
            '453-680g'
        ),
        (
            25,
            'Papaye',
            '33-38cm',
            '0,77-1,22kg'
        ),
        (
            26,
            'Papaye',
            '33-38cm',
            '0,77-1,22kg'
        ),
        (
            27,
            'Papaye',
            '33-38cm',
            '0,77-1,22kg'
        ),
        (
            28,
            'Papaye',
            '33-38cm',
            '0,77-1,22kg'
        ),
        (
            29,
            'Potiron',
            '38-43cm',
            '1,36-2kg'
        ),
        (
            30,
            'Potimarron',
            '38-43cm',
            '1,36-2kg'
        ),
        (
            31,
            'Potimarron',
            '38-43cm',
            '1,36-2kg'
        ),
        (
            32,
            'Potimarron',
            '38-43cm',
            '1,36-2kg'
        ),
        (
            33,
            'Melon Oriental',
            '43-48cm',
            '2-2,9kg'
        ),
        (
            34,
            'Melon Oriental',
            '43-48cm',
            '2-2,9kg'
        ),
        (
            35,
            'Melon Oriental',
            '43-48cm',
            '2-2,9kg'
        ),
        (
            36,
            'Melon Oriental',
            '43-48cm',
            '2-2,9kg'
        ),
        (
            37,
            'Pastèque',
            '48-52cm',
            '3-3,6kg'
        ),
        (
            38,
            'Pastèque',
            '48-52cm',
            '3-3,6kg'
        ),
        (
            39,
            'Pastèque',
            '48-52cm',
            '3-3,6kg'
        ),
        (
            40,
            'Pastèque',
            '48-52cm',
            '3-3,6kg'
        );